[package]
name = "retis"
version = "0.1.0"
edition = "2021"

[features]
test_bindgen_layout = []
test_cap_bpf = []

[dependencies]
anyhow = "1.0"
bimap = "0.6"
btf-rs = "0.1"
byteorder = "1.4"
clap = { version = "4.0", features = ["derive", "string"] }
elf = "0.7"
libbpf-rs = {git = "https://github.com/libbpf/libbpf-rs.git", rev= "52ab250"}
libbpf-sys = "1.0"
libc = "0.2"
log = "0.4"
nix = "0.25"
once_cell = "1.15"
plain = "0.2"
serde_json = "1.0"
signal-hook = "0.3"
simplelog = "0.12"
thiserror = "1.0"

[build-dependencies]
bindgen = "0.63"
libbpf-cargo = "0.13"
libbpf-sys = "1.0"
memmap2 = "0.5"

[dev-dependencies]
probe = "0.3.0"
