site_name: Retis
site_description: Documentation for Retis, the Linux packet tracing tool
site_author: The Retis community
site_url: https://retis.readthedocs.io/
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/retis-org/retis

nav:
  - Overview: index.md
  - Profiles: profiles.md
  - Filtering: filtering.md
  - Installation: install.md
  - Requirements: requirements.md
  - Contributing: CONTRIBUTING.md
  - External resources: resources.md
  - Event sections: event_sections.md
  - Python bindings: python.md
  - Collectors:
      - skb: modules/skb.md
      - skb-drop: modules/skb_drop.md
      - skb-tracking: modules/skb_tracking.md
      - ovs: modules/ovs.md
      - ct: modules/ct.md
      - nft: modules/nft.md

theme: readthedocs
plugins:
  - search
