site_name: Retis
site_description: Documentation for Retis, the Linux packet tracing tool
site_author: The Retis community
site_url: https://retis.readthedocs.io/
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/retis-org/retis
edit_uri: edit/main/docs/

nav:
    - Getting started:
        - Overview: index.md
        - Requirements: requirements.md
        - Installation: install.md
    - Collectors:
        - Event sections: collectors/event_sections.md
        - skb: collectors/skb.md
        - skb-drop: collectors/skb_drop.md
        - skb-tracking: collectors/skb_tracking.md
        - ovs: collectors/ovs.md
        - ct: collectors/ct.md
        - nft: collectors/nft.md
    - Learn more:
        - Filtering: filtering.md
        - Profiles: profiles.md
        - Python bindings: python.md
        - Limitations: limitations.md
    - Resourses:
        - External: resources.md
        - Contributing: CONTRIBUTING.md

markdown_extensions:
  - footnotes

theme: readthedocs
plugins:
  - search
